### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by wilg** [yhirano55/apple_music#5]
```
TypeError: no implicit conversion of nil into String
  from apple_music (c78cf4ffa6fe) lib/apple_music/song/attributes.rb:30:in `parse'
  from apple_music (c78cf4ffa6fe) lib/apple_music/song/attributes.rb:30:in `initialize'
  from apple_music (c78cf4ffa6fe) lib/apple_music/resource.rb:37:in `new'
  from apple_music (c78cf4ffa6fe) lib/apple_music/resource.rb:37:in `initialize'
  from apple_music (c78cf4ffa6fe) lib/apple_music/resource.rb:27:in `new'
  from apple_music (c78cf4ffa6fe) lib/apple_music/resource.rb:27:in `build'
  from apple_music (c78cf4ffa6fe) lib/apple_music/relationship.rb:20:in `block in build_list'
  from apple_music (c78cf4ffa6fe) lib/apple_music/relationship.rb:20:in `map'
  from apple_music (c78cf4ffa6fe) lib/apple_music/relationship.rb:20:in `build_list'
  from apple_music (c78cf4ffa6fe) lib/apple_music/relationship.rb:11:in `initialize'
  from apple_music (c78cf4ffa6fe) lib/apple_music/search_result.rb:16:in `new'
  from apple_music (c78cf4ffa6fe) lib/apple_music/search_result.rb:16:in `initialize'
  from apple_music (c78cf4ffa6fe) lib/apple_music/search.rb:20:in `new'
  from apple_music (c78cf4ffa6fe) lib/apple_music/search.rb:20:in `search'
  from apple_music (c78cf4ffa6fe) lib/apple_music.rb:35:in `search'
  from apple_music (c78cf4ffa6fe) lib/apple_music/song.rb:74:in `search'
```

**Comment by johncjensen** [comment]
Having the same issue, @wilg did you find a fix?
